# Default values for aws-alb-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Resources created by the ALB Ingress controller will be prefixed with this string
## Required
clusterName: ${cluster_name}

## AWS region of k8s cluster, required if ec2metadata is unavailable from controller pod
## Required if autoDiscoverAwsRegion != true
awsRegion: ${region}

## VPC ID of k8s cluster, required if ec2metadata is unavailable from controller pod
## Required if autoDiscoverAwsVpcID != true
awsVpcID: ${vpc_id}

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": ${role-arn}